In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1.shape)
print(arr1.ndim)
print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)

(5,)
1
4
5
int32


In [14]:
np.arange(0,10,1).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#vetcorized operation
ar1 = np.array([1,2,3,4,5])
ar2 =np.array([10,20,30,40,50])

print("addition:" , ar1+ar2)
print("subtraction",ar1-ar2)
print("multiplication", ar1*ar2)
print("division", ar1/ar2)

addition: [11 22 33 44 55]
subtraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [ ]:
#universal functions
print(np.sqrt(ar1))
print(np.sin(ar1))
print(np.log(ar1))
print(np.exp(ar1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
arr[0][1]

np.int64(2)

In [21]:
arr[0,1]

np.int64(2)

In [24]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [25]:
arr[1, 2:]

array([ 8,  9, 10])

In [15]:
#statsistical concepts- normalization
#to have a mean of 0 and standard deviation of 1
data = np.array([1,3,4,6,7])

#mean and std deviation
mean = np.mean(data)
std = np.std(data)
print(mean)

#normalize data
normalized_data = (data-mean)/std

print("normalized data: ",normalized_data)


4.2
normalized data:  [-1.4985373  -0.56195149 -0.09365858  0.84292723  1.31122014]


In [32]:
data = np.array([1,2,3,4,5,6,7,8,9])

#mean
print(np.mean(data))
#median
print(np.median(data))
#std
print(np.std(data))
#variance
print(np.var(data))

5.0
5.0
2.581988897471611
6.666666666666667


In [31]:
data[data>5]

array([6, 7, 8, 9])

In [33]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [35]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

[67 93 99 18 84]
